[IV-22-23] Objetivo 1
jesusjmma/Proyecto-Infraestructura-Virtual pull request #5
Opened 2022-10-22 09:01 UTC by jesusjmma

## Prerequisitos
* [x] Objetivo 0 entregado sin errores.

## Lista de comprobación
### Sobre los milestones
* [x] **¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?**
Sí. Definen, como poco, una primera visión del camino de desarrollo a recorrer.
* [x] **¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?**
Sí. Están en el orden de realización del proyecto.
* [x] **¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?**
Sí. De hecho no tiene sentido realizar un milestone si no se han completado todos los anteriores.
* [x] **¿El milestone 0 tiene asignada alguna historia de usuario?**
Sí. [El milestone 0 (el 1 en mi caso)](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/1) es la creación de las estructuras de datos y necesita de las historias de usuario creadas para poder entender los datos a usar y las estructuras a crear.
* [x] **¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?**
Sí. Misma explicación dada como respuesta a la pregunta anterior.
* [x] **¿Todos los milestones describen correctamente un producto, y no un concepto vago, una funcionalidad o una tarea?**
Sí. Cada uno de ellos describe un producto final de etapa.
* [x] **¿Los milestones son graduales, o hay un salto grande entre ellos?**
Son graduales, no hay saltos grandes entre ellos.
* [x] **¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?**
Sí. Los dos primeros milestones ([M1](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/1) y [M2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/2)) son internos, ya que no se corresponden con un producto útil para un usuario. Sin embargo los dos siguientes milestones ([M3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/3) y [M4](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/4)) son externos.
* [x] **¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?**
Sí. Todos ellos incluyen un producto final de etapa con el que poder avanzar.
* [x] **¿El milestone 0 es mínimo *y* viable?**
Sí. Se trata de la creación de las estructuras de datos.
* [x] **¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?**
Sí. En cada milestone se indican los requisitos técnicos que se deben de conseguir para comprobar la viabilidad del producto mínimo viable.
* [x] **¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?**
Entre dos milestones consecutivos no hay un producto mínimo viable intermedio. Si lo hubiese habría creado un nuevo milestone entre dichos dos.

### Sobre las historias de usuario
* [x] **¿He tenido en cuenta en las historias de usuario que se trata de un proyecto que se desplegará en la nube?**
Sí. Lo he tenido en cuenta.
* [x] **¿Están descritos todos los conceptos mencionados en las HUs con suficiente claridad, generalmente en documentos aparte?**
Sí. Está creado todo en el documento [user-stories.md](../blob/Objetivo-1/docs/user-stories.md) así como en los issues [HU1](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/2), [HU2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/3) y [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4).
* [x] **¿Tienen coherencia suficiente las historias de usuario, y en caso de que no lo tengan, se ha escrito un *user journey* para aclararlo?**
Sí. Las historias de usuario están descritas con coherencia y claridad suficiente. Se pueden ver en el documento mencionado en la respuesta anterior.
* [x] **¿Todas las historias de usuario representan un beneficio para el mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?**
Sí. Todas las historias de usuario están relacionadas con la lógica de negocio.

2022-10-22 11:30 UTC, Carlos-SE requested changes

2022-10-22 11:30 UTC, Carlos-SE commented on docs/milestones.md
> +## [M1] Creación de la estructura de datos
El primer milestone tiene que ser el `M0`, también tiene que ser un PMV (la creación de algo no lo es).

2022-10-22 11:41 UTC, jesusjmma commented on docs/milestones.md
> +## [M1] Creación de la estructura de datos
Hola @Carlos-SE. Te comento mis dudas sobre lo que dices:
- Según dice en la segunda pregunta de comprobación, he entendido que los Milestones los podías empezar por 0 o por 1. ¿O he entendido mal la pregunta de comprobación? De igual forma también sale como ejemplo en [esta diapositiva](https://jj.github.io/IV/preso/pmv.html#/8/0/0) que empieza por el Milestone 1.
- Y sobre lo del PMV, según he visto en [esta otra diapositiva](https://jj.github.io/IV/preso/pmv.html#/9) lo de la estructura de datos sí sirve como Milestone. ¿El problema es simplemente al expresarlo con la palabra _creación_?

¡Gracias por la ayuda!

2022-10-22 11:54 UTC, Carlos-SE commented on docs/milestones.md
> +## [M1] Creación de la estructura de datos
Buenas tardes @jesusjmma, perdóname por no haberme presentado. 

- Te contesto a la primera pregunta; a la hora de comenzar con los milestones se concretó que el `M0` sería el que representase al modelo del problema (yo también empecé en el `M1`, así que te lo digo con experiencia :smiling_face_with_tear: ) A partir del primer milestone los demás tienen que seguir un orden y creo que lo has establecido correctamente. Sería sólo comenzar por `M0`.

- Sobre la sengunda duda: Tienes razón, la cosa que distingue es que la creación de algo no es tangible, en cambio, una base de datos, un archivo, fichero, etc. (cosas entregables) si cumplen la carácterística de ser un `PMV` ya que describe un producto, justo en la [diapositíva que has adjuntado](https://jj.github.io/IV/preso/pmv.html#/9) se puede ver que especifica un modelo, ya que la representación de las estructuras de datos que necesites y de tu lógica de negocio se modelizan y eso si constituye un `PMV`.

Espero que te haya aclarado las cosas, sino no dudes en preguntarme.
¡Mucho ánimo! :+1:

2022-10-22 12:04 UTC, jesusjmma commented on docs/milestones.md
> +## [M1] Creación de la estructura de datos
Fantástico. Gracias por la explicación 😁
Ese par de erratas ya están cambiadas tanto en los Milestone de GitHub como en los archivos que los describen.

2022-10-22 12:08 UTC, Carlos-SE commented on docs/milestones.md
> +Enlace al milestone: [M1](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/2)
Aquí se te ha pasado cambiarlo :face_in_clouds:

2022-10-22 12:09 UTC, Carlos-SE commented on docs/milestones.md
> +Enlace al milestone: [M1](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/2)
En los encabezados me refiero

2022-10-22 12:15 UTC, jesusjmma commented on docs/milestones.md
> +Enlace al milestone: [M1](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/2)
Cierto. Si es que quien me mandará a mí mencionar tantas veces la misma cosa...
Ya debería estar eso también corregido. ¡Gracias!

2022-10-22 12:16 UTC, Carlos-SE commented on docs/milestones.md
> +Enlace al milestone: [M1](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/2)
:+1:

2022-10-22 12:18 UTC, Carlos-SE commented
Esperamos a que alguien más te revise el PR, sino lo hace nadie en un par de días, menciona al profesor y que te lo revise, por mi parte no veo nada a remarcar.

Buen trabajo! :smile:

2022-10-23 08:00 UTC, JJ requested changes
Por favor, revisa el concepto de milestone / producto mínimamente viable y el de historia de usuario.

2022-10-23 08:00 UTC, JJ commented on docs/user-stories.md
> +## María Teresa de Uña
No veo claro qué beneficio hay para cada usuario, ni en qué influye en la lógica de negocio.

2022-10-23 08:02 UTC, JJ commented on docs/milestones.md
> +## [M1] Creación de la estructura de datos
> Buenas tardes @jesusjmma, perdóname por no haberme presentado.
> 
>     * Te contesto a la primera pregunta; a la hora de comenzar con los milestones se concretó que el `M0` sería el que representase al modelo del problema (yo también empecé en el `M1`, así que te lo digo con experiencia smiling_face_with_tear ) A partir del primer milestone los demás tienen que seguir un orden y creo que lo has establecido correctamente. Sería sólo comenzar por `M0`.
> 
>     * Sobre la sengunda duda: Tienes razón, la cosa que distingue es que la creación de algo no es tangible, en cambio, una base de datos, un archivo, fichero, etc. (cosas entregables) si cumplen la carácterística de ser un `PMV` ya que describe un producto, justo en la [diapositíva que has adjuntado](https://jj.github.io/IV/preso/pmv.html#/9) se puede ver que especifica un modelo, ya que la representación de las estructuras de datos que necesites y de tu lógica de negocio se modelizan y eso si constituye un `PMV`.
> 
> 
> Espero que te haya aclarado las cosas, sino no dudes en preguntarme. ¡Mucho ánimo! +1

Aquí te está diciendo claramente que se trata de representar el modelo del problema. ¿Por qué no le has hecho caso?

2022-10-23 08:04 UTC, JJ commented
Tampoco veo claro que estas historias de usuario reflejen claramente lo que dijiste en el #1. No se trata de una aplicación para compartir gastos ni reducir los pagos entre grupos que no están establecidos, sino la típica aplicación de compartir gastos entre grupos. Por favor, ajústate al proyecto original y trata de reflejarlo en las HUs.

2022-10-23 16:01 UTC, jesusjmma commented
Listo para revisión, @JJ.

He realizado las siguientes modificaciones:
- Reescrito el [M0](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/1).
- Eliminado el Milestone que hablaba sobre interfaz gráfica.
- Creado los [user journeys](../blob/Objetivo-1/docs/user-journeys.md) y los [user-stories](../blob/Objetivo-1/docs/user-stories.md), ampliando y redactando lo anterior de forma más clara y relacionándolo con la lógica de negocio indicada en el #1.

2022-10-23 17:00 UTC, JJ requested changes
Por favor, tened en cuenta todos los comentarios y modificad la línea en la que se hayan hecho o contestad diciendo cómo lo resolvéis.

2022-10-23 17:00 UTC, JJ commented on docs/milestones.md
> +## [M0] Modulo que defina la estructura de datos
:arrow_up:

2022-10-23 17:00 UTC, JJ commented on docs/user-stories.md
> +## Lucas de la Rosa
:arrow_up:

2022-10-23 17:42 UTC, jesusjmma commented on docs/milestones.md
> +## [M0] Modulo que defina la estructura de datos
Me había faltado actualizar el encabezado justo ahí. Ya lo he actualizado tal y como está en [M0](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/milestone/1).

2022-10-23 17:43 UTC, jesusjmma commented on docs/milestones.md
> +## [M2] Interfaz de usuario
He quitado ese milestone.

2022-10-23 17:43 UTC, jesusjmma commented on docs/milestones.md
> +## [M3] Despliegue en la nube
He quitado el milestone de la interfaz de usuario.

2022-10-23 17:45 UTC, jesusjmma commented on docs/user-stories.md
> +## Lucas de la Rosa
He actualizado el documento y dejado aquí las historias de usuario y he creado otro documento con los _user journeys_. El documento creado nuevo es [user journeys](../blob/Objetivo-1/docs/user-journeys.md).

2022-10-23 17:45 UTC, jesusjmma commented on docs/user-stories.md
> +## María Teresa de Uña
He mejorado la descripción de las historias de usuario para que se vea la necesidad de la lógica de negocio en cada uno de los usuarios.

2022-10-23 17:47 UTC, jesusjmma commented
> Por favor, tened en cuenta todos los comentarios y modificad la línea en la que se hayan hecho o contestad diciendo cómo lo resolvéis.

Tomo nota de ello. Gracias por avisar.
He respondido ya a los diferentes comentarios con la resolución de cada fallo. De igual forma he actualizado el archivo [milestones.md](../blob/Objetivo-1/docs/milestones.md) puesto que me había faltado actualizar ahí el encabezado.

2022-10-23 18:53 UTC, JJ approved these changes
:+1:

2022-10-23 18:55 UTC, JJ commented
Por favor, empieza inmediatamente con el objetivo 2 para poder alcanzar los 5 objetivos mínimos en la convocatoria ordinaria.

2022-10-23 22:30 UTC, merged