[IV 22-23] : Objetivo 2
jesusjmma/Proyecto-Infraestructura-Virtual pull request #9
Opened 2022-11-21 12:48 UTC by danielsp13

***Sobre la estructura del repositorio:***
* [ ] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?

***Sobre el análisis del problema:***
* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

***Sobre la planificación y la programación:***
* [ ] ¿Los issues representan un problema, y no una tarea?
* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están asignados a una HU?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?
* [ ] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2022-11-21 12:51 UTC, danielsp13 commented
Buenas tardes Jesús. En este PR que he creado, podrás ver todo el desarrollo para el Objetivo 2. He estado esperando unos días para resolver los _issues_ abiertos, pero no he recibido ningún feedback, así que continúo el desarrollo del código que tengo actualmente hasta que puedas responderme. Te mencionaré explícitamente tanto a ti como al profesor una vez considere que el objetivo puede estar superado.

2022-11-22 09:41 UTC, danielsp13 commented
Tanto para el profesor como para jesús. En este punto me he dado cuenta de que no estoy referenciando correctamente los _issues_ debido a que me confundí de número de tarea, procedo a cambiar los commits.

2022-11-22 10:04 UTC, danielsp13 commented
Ya está solucionado. He utilizado la siguiente página para poder hacer esto... [change git commit after push](https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push). ¡uf!

2022-11-23 08:47 UTC, JJ commented
Por favor, sigue las mejores prácticas en los mensajes de commit. Estos no pueden repetir lo que es evidente.

2022-11-23 09:01 UTC, JJ commented
> Ya está solucionado. He utilizado la siguiente página para poder hacer esto... [change git commit after push](https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push). ¡uf!

La mala práctica de hacer force push es peor que la mala práctica de no hacer mensajes de commit incorrectos. En todo caso, siguen siendo incorrectos.
@jesusjmma, hace dos días que @danielsp13 ha hecho este PR. Tienes que asignarlo a un milestone, o @danielsp13 no podrá hacer el PR. Por favor, hazlo a lo largo del día de hoy para no impedir avanzar en este objetivo a tu compañero.

2022-11-23 09:06 UTC, danielsp13 commented
> > Ya está solucionado. He utilizado la siguiente página para poder hacer esto... [change git commit after push](https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push). ¡uf!
> 
> La mala práctica de hacer force push es peor que la mala práctica de no hacer mensajes de commit incorrectos. En todo caso, siguen siendo incorrectos. @jesusjmma, hace dos días que @danielsp13 ha hecho este PR. Tienes que asignarlo a un milestone, o @danielsp13 no podrá hacer el PR. Por favor, hazlo a lo largo del día de hoy para no impedir avanzar en este objetivo a tu compañero.

Qué mal :disappointed: ... la verdad que me vi apurado porque me equivoqué al etiquetar correctamente la tarea que correspondía. ¿Es necesario que cambie de alguna forma los commits que ya tengo? ¿O continúo a partir de aquí ya de la manera adecuada?

2022-11-23 09:07 UTC, danielsp13 commented
En cualquier caso, me sirve de experiencia... mirar dos veces bien antes de hacer commit :crossed_fingers:

2022-11-23 09:11 UTC, JJ commented
> > > Ya está solucionado. He utilizado la siguiente página para poder hacer esto... [change git commit after push](https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push). ¡uf!
> > 
> > 
> > La mala práctica de hacer force push es peor que la mala práctica de no hacer mensajes de commit incorrectos. En todo caso, siguen siendo incorrectos. @jesusjmma, hace dos días que @danielsp13 ha hecho este PR. Tienes que asignarlo a un milestone, o @danielsp13 no podrá hacer el PR. Por favor, hazlo a lo largo del día de hoy para no impedir avanzar en este objetivo a tu compañero.
> 
> Qué mal disappointed ... la verdad que me vi apurado porque me equivoqué al etiquetar correctamente la tarea que correspondía. ¿Es necesario que cambie de alguna forma los commits que ya tengo? ¿O continúo a partir de aquí ya de la manera adecuada?

Por lo pronto, no hagas nada hasta que @jesusjmma responda, porque si no lo hace, lo mejor para que sigas avanzando es trabajar en otro repositorio.

2022-11-23 09:23 UTC, danielsp13 commented
> > > > Ya está solucionado. He utilizado la siguiente página para poder hacer esto... [change git commit after push](https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push). ¡uf!
> > > 
> > > 
> > > La mala práctica de hacer force push es peor que la mala práctica de no hacer mensajes de commit incorrectos. En todo caso, siguen siendo incorrectos. @jesusjmma, hace dos días que @danielsp13 ha hecho este PR. Tienes que asignarlo a un milestone, o @danielsp13 no podrá hacer el PR. Por favor, hazlo a lo largo del día de hoy para no impedir avanzar en este objetivo a tu compañero.
> > 
> > 
> > Qué mal disappointed ... la verdad que me vi apurado porque me equivoqué al etiquetar correctamente la tarea que correspondía. ¿Es necesario que cambie de alguna forma los commits que ya tengo? ¿O continúo a partir de aquí ya de la manera adecuada?
> 
> Por lo pronto, no hagas nada hasta que @jesusjmma responda, porque si no lo hace, lo mejor para que sigas avanzando es trabajar en otro repositorio.

De acuerdo. Estaré a la espera.

2022-11-24 00:17 UTC, jesusjmma approved these changes
Creo que has hecho un gran trabajo @danielsp13. Disculpa por no haberte contestado antes.
He visto todos los archivos y creo que están perfectos para avanzar el milestone.

2022-11-24 12:06 UTC, danielsp13 commented
> Creo que has hecho un gran trabajo @danielsp13. Disculpa por no haberte contestado antes y por no haber podido avisar (cc: @JJ). He visto todos los archivos y creo que están perfectos para avanzar el milestone.

Gracias por ver todo lo que he hecho, pero todavía no es suficiente como para que todo el objetivo esté completado. Me falta por definir una serie de cuestiones que cito a continuación:
- Definir claramente qué es un objeto valor y qué una entidad (y una vez hecho eso, documentarlo en un fichero README dentro del directorio del código src/).
- Definir las entidades en el fichero iv.yaml
- Terminar la definición e implementación de ciertos métodos importantes para la lógica de negocio de este proyecto. Hay algunos aspectos que no me terminan de convencer todavía, y tengo que estar seguro de que se ajusta a lo que se requiere y es de acorde con las historias de usuario correspondientes. Además, me falta por testear un par de cosas.

En cuanto haga todo esto, enlazaré este PR al documento de objetivos y pediré la revisión al profesor. Te notificaré de más cambios que haga.

2022-11-24 16:14 UTC, jesusjmma commented
> > Creo que has hecho un gran trabajo @danielsp13. Disculpa por no haberte contestado antes y por no haber podido avisar (cc: @JJ). He visto todos los archivos y creo que están perfectos para avanzar el milestone.
> 
> Gracias por ver todo lo que he hecho, pero todavía no es suficiente como para que todo el objetivo esté completado. Me falta por definir una serie de cuestiones que cito a continuación:
> 
> * Definir claramente qué es un objeto valor y qué una entidad (y una vez hecho eso, documentarlo en un fichero README dentro del directorio del código src/).
> * Definir las entidades en el fichero iv.yaml
> * Terminar la definición e implementación de ciertos métodos importantes para la lógica de negocio de este proyecto. Hay algunos aspectos que no me terminan de convencer todavía, y tengo que estar seguro de que se ajusta a lo que se requiere y es de acorde con las historias de usuario correspondientes. Además, me falta por testear un par de cosas.
> 
> En cuanto haga todo esto, enlazaré este PR al documento de objetivos y pediré la revisión al profesor. Te notificaré de más cambios que haga.

Perfecto. Pues me mantengo a la espera.

2022-11-24 16:26 UTC, danielsp13 commented
Comienzo el trabajo de hoy en la rama:
- Arreglando commits ajustándose a las buenas prácticas.

2022-11-24 22:26 UTC, danielsp13 commented
Buenas noches @jesusjmma . Esto está listo para revisión.

2022-11-24 22:33 UTC, danielsp13 commented
En este comentario dejo unas indicaciones complementarias a la documentación que he aportado:

- Todo el código que he implementado ha sido respaldado por las historia de usuario [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4) que es la que está asociada al milestone M0, y además por la historia de usuario [HU2](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/3), ya que como te indiqué, encontré problemas a la hora de modelar correctamente la diferencia entre un *gasto* y una *deuda*, además de la relación entre *usuarios*, *gastos* y *deudas*. Es por ello por lo que tomé la decisión de definir la entidad *gastoCompartido* que es la que me permite modelar correctamente todas estas historias. 
- Todo el código ha sido probado y testeado adecuadamente. Los métodos implementados para las diferentes clases se han implementado por bloques, es decir, he ido definiendo lo que necesito, después implementándolo, y por último testeándolo verificando que la sintaxis es correcta y no se producen errores.
- Considero que lo que he realizado es un PMV que satisface el M0 del proyecto, puesto que las historias de usuario (entre ellas la asociada), han sido verificadas. Tienes todo lo necesario para poder comenzar a avanzar con el siguiente hito.

2022-11-24 22:34 UTC, danielsp13 commented
Una vez se hayan aprobado todos los cambios en la rama por tu parte y por el profesor, procederé a limpiar la zona de tests de todos los ficheros y emitiré el commit de cierre de las tareas correspondientes.

2022-11-25 09:28 UTC, dmonjasm commented
@danielsp13 Para los mensajes de commit en vez de poner Avanaza XXXX, creo que el formato correcto es la acción realizada (Creo, Modifico, Borro, etc.) junto con la modificación hecha. Y ya luego le enlazas el issue o el PR. Te adjunto un link de best practices para commits [Best practices](https://www.freecodecamp.org/news/git-best-practices-commits-and-code-reviews)

2022-11-25 09:43 UTC, danielsp13 commented
> @danielsp13 Para los mensajes de commit en vez de poner Avanaza XXXX, creo que el formato correcto es la acción realizada (Creo, Modifico, Borro, etc.) junto con la modificación hecha. Y ya luego le enlazas el issue o el PR. Te adjunto un link de best practices para commits [Best practices](https://www.freecodecamp.org/news/git-best-practices-commits-and-code-reviews)

Gracias por la corrección @dmonjasm ... Seguiré lo que me has dicho, pero cuando dices:

> Y ya luego le enlazas el issue o el PR.

¿Dónde va exactamente esta parte? Es lo que no termino de entender

Y otra cuestión. ¿Sabes cómo puedo modificar dichos commits sin que haga un `push --force`?

2022-11-25 09:50 UTC, dmonjasm commented
Pues leyendo distintas páginas de good practices parace ser que la buena práctica en general viene a ser algo como,
- [#issue] Creada clase algo.

Pero por si acaso que lo confirme @JJ.

En cuanto a tu segunda pregunta la verdad que no tengo tanto dominio de git así que no te se decir. Creo que si no sabes como hacerlo y nadie te puede explicar como lo mejor sería que dejes los mensajes como están y empieces a aplicar las buenas prácticas a los siguientes, ya que si que se que un git force es un mala práctica.

2022-11-25 10:02 UTC, danielsp13 commented
> Pues leyendo distintas páginas de good practices parace ser que la buena práctica en general viene a ser algo como,
> 
> * [#issue] Creada clase algo.
> 
> Pero por si acaso que lo confirme @JJ.
> 
> En cuanto a tu segunda pregunta la verdad que no tengo tanto dominio de git así que no te se decir. Creo que si no sabes como hacerlo y nadie te puede explicar como lo mejor sería que dejes los mensajes como están y empieces a aplicar las buenas prácticas a los siguientes, ya que si que se que un git force es un mala práctica.

De acuerdo. Me gustaría arreglarlo realmente para seguir las mejores prácticas en este objetivo, pero bueno me quedo con la corrección si no es posible hacer nada mejor que un `push --force` y lo aplicaré a la próxima. Gracias @dmonjasm , ahora sí me ha quedado claro esto.

2022-11-25 11:56 UTC, JJ commented
> Pues leyendo distintas páginas de good practices parace ser que la buena práctica en general viene a ser algo como,
> 
>     * [#issue] Creada clase algo.
> 

No, porque ya sabes lo que estás haciendo y creando sólo mirando el código. Tienes que poner cosas que no estén en el commit ni en sus metadatos: por qué has hecho eso, con qué issue estás trabajando, y por qué crees que eso resuelve el problema.

2022-11-25 11:57 UTC, JJ commented
> > Pues leyendo distintas páginas de good practices parace ser que la buena práctica en general viene a ser algo como,
> > 
> > * [#issue] Creada clase algo.
> > 
> > Pero por si acaso que lo confirme @JJ.
> > En cuanto a tu segunda pregunta la verdad que no tengo tanto dominio de git así que no te se decir. Creo que si no sabes como hacerlo y nadie te puede explicar como lo mejor sería que dejes los mensajes como están y empieces a aplicar las buenas prácticas a los siguientes, ya que si que se que un git force es un mala práctica.
> 
> De acuerdo. Me gustaría arreglarlo realmente para seguir las mejores prácticas en este objetivo, pero bueno me quedo con la corrección si no es posible hacer nada mejor que un `push --force` y lo aplicaré a la próxima. Gracias @dmonjasm , ahora sí me ha quedado claro esto.

Es muy mala costumbre usar push --force. Estamos hablando de una convención, no de una funcionalidad y menos de cara al cliente. Simplemente usa las convenciones correctas de ahora en adelante.

2022-11-25 17:44 UTC, jesusjmma approved these changes
Por mi parte está perfecto @danielsp13.
He revisado todo lo que se indica en el Objetivo 2 y creo que se cumple con lo que has hecho. Además el README me ha parecido muy bien explicado con todo lo que has llevado a cabo.

2022-11-25 19:14 UTC, JJ requested changes
Creo que tenéis que revisar el concepto de producto *mínimo* viable.
Limitaros a implementar la estructura de datos del modelo.

2022-11-25 19:14 UTC, JJ commented on iv.yaml
> +lenguaje: python3
No es un lenguaje. Es una versión. La única que hay ahora mismo en desarrollo.

2022-11-25 19:14 UTC, JJ commented on src/deuda.py
> +    #Usuario que recibe la deuda
Es mejor que sólo pongas docstrings como documentación.

2022-11-25 19:14 UTC, JJ commented on src/deuda.py
> +    def __str__(self):
Esto no lo pide el milestone actual.

2022-11-25 19:14 UTC, JJ commented on src/deuda.py
> +    id: int
Los objetos valor no tienen indentidad, son indistinguibles. ¿Por qué querrías ponerle un id? ¿Hay alguna información más aparte del los otros atributos?

2022-11-25 19:14 UTC, JJ commented on src/deuda.py
> +        return self.usuarioDeber.nickname
¿Qué HU dice que hace falta esto?

2022-11-25 19:14 UTC, JJ commented on src/deuda.py
> +if __name__ == "__main__":
¿En qué HU/milestone dice qeu hace falta esto?

2022-11-25 19:14 UTC, JJ commented on src/gasto.py
> +    id: int
Una vez más, los objetos valor no tienen ID. Y tampoco hacen falta.

2022-11-25 19:14 UTC, JJ commented on src/gasto.py
> +if __name__ == "__main__":
????

2022-11-25 19:14 UTC, JJ commented on src/gastoCompartido.py
> +        for usuario in usuarios:
Un "modelo" implica que no debe haber ninguna funcionalidad. No entiendo tampoco por qué pones esta función y no el constructor.

2022-11-25 19:14 UTC, JJ commented on src/gastoCompartido.py
> +    def __buscarGastosPorNick(self,nick):
Ninguna funcionalidad en el modelo.

2022-11-25 19:22 UTC, danielsp13 commented
Todo recibido y leído @JJ , aplicaré todos los cambios indicados en cuanto pueda y volveré a mencionarle. Gracias.

2022-11-25 19:23 UTC, JJ commented
> Todo recibido y leído @JJ , aplicaré todos los cambios indicados en cuanto pueda y volveré a mencionarle. Gracias.

A ti.

2022-11-26 10:39 UTC, JJ commented on src/usuario.py
> +    def obtenerListaDeudas(self):
Creo que os dije bastante claramente que un modelo del problema no incluye getters ni setters. Si se incluye en el milestone, está mal. Por favor, tratad de entender el concepto de producto *mínimamente* viable para evitar trabajo innecesario (por vuestra parte y la mía)

2022-11-26 10:45 UTC, danielsp13 commented on src/usuario.py
> +    def obtenerListaDeudas(self):
De acuerdo.

2022-11-26 11:10 UTC, danielsp13 commented
@JJ . Considero que ahora sí que he realizado todos los cambios oportunos para ajustarme a lo que se requiere en este milestone. Está listo para revisión.

2022-11-28 10:40 UTC, JJ commented
Commits como [983ef8c](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/pull/9/commits/983ef8c46679f652552daf3d02b994e4b92189c2) no siguen las mejores prácticas. En otros sólo repites lo que es obvio mirando el diff (modifico x eliminando y → información ya en el diff)

2022-11-28 10:50 UTC, JJ requested changes
Dado que no se plantean claramente los problemas, ni se refiere a ellos de forma estricta (una referencia genérica a #7 y #8 no ayuda en nada), es complicado aplicar un análisis DDD correcto, que halle las clases más adecuadas.

Sería conveniente que plantearas nuevos issues que sean de verdad problemas, y que cuando modificques o borres las partes de código existente que no sean adecuadas hagas un `closes` de estos issues que son "aclaraciones", no "problemas" (como has marcado en el cuerpo)

2022-11-28 10:50 UTC, JJ commented on src/gastoCompartido.py
> +    usuarios de la aplicacion, y donde todos tienen una aportacion, ya sea
typo: aportación

2022-11-28 10:50 UTC, JJ commented on src/infoUsuario.py
> +    nickname: str
No hay ninguna historia de usuario que requiera este atributo.

2022-11-28 10:50 UTC, JJ commented on src/infoUsuario.py
> +    nombre: str
Ninguna historia de usuario requiere que nombre y apellidos estén separados.

2022-11-28 10:50 UTC, JJ commented on src/usuario.py
> +        self.__usuario = u
Lo único que se requiere aquí es que se identifique el usuario de forma única. Esto por un lado no lo garantiza (porque es una simple variable). Suponemos que es infoUsuario (esta importación no se usa de todas formas), pero si es así, es bastante complicado, por ejemplo, buscar las deudas de un usuario específico (porque infousuario tiene tres campos)

2022-11-28 10:50 UTC, JJ commented on src/usuario.py
> +        self.__deudas = [deuda for deuda in deudas if deuda.usuarioDeudor.nickname == self.__usuario.nickname]
¿Lo ves como es complicado?

2022-11-28 11:15 UTC, danielsp13 commented
> Dado que no se plantean claramente los problemas, ni se refiere a ellos de forma estricta (una referencia genérica a #7 y #8 no ayuda en nada), es complicado aplicar un análisis DDD correcto, que halle las clases más adecuadas.
> 
> Sería conveniente que plantearas nuevos issues que sean de verdad problemas, y que cuando modificques o borres las partes de código existente que no sean adecuadas hagas un `closes` de estos issues que son "aclaraciones", no "problemas" (como has marcado en el cuerpo)

Todo leído. Gracias por la corrección. Hay algunos aspectos que ahora mismo no comprendo de la corrección en sí, pero creo que es trabajo mío precisamente planteando los issues correctos con sus correspondientes problemas.

2022-11-28 11:31 UTC, JJ commented
> > Dado que no se plantean claramente los problemas, ni se refiere a ellos de forma estricta (una referencia genérica a #7 y #8 no ayuda en nada), es complicado aplicar un análisis DDD correcto, que halle las clases más adecuadas.
> > Sería conveniente que plantearas nuevos issues que sean de verdad problemas, y que cuando modificques o borres las partes de código existente que no sean adecuadas hagas un `closes` de estos issues que son "aclaraciones", no "problemas" (como has marcado en el cuerpo)
> 
> Todo leído. Gracias por la corrección. Hay algunos aspectos que ahora mismo no comprendo de la corrección en sí, pero creo que es trabajo mío precisamente planteando los issues correctos con sus correspondientes problemas.

Ha mejorado bastante con respecto a la última iteración. He puesto algunos errores frecuentes en la semana 12 que es posible que te ayuden. Si no, simplemente pregunta.

2022-11-28 14:33 UTC, danielsp13 commented
@jesusjmma . A partir de aquí, empiezo de 0 con la resolución del hito M0. Procedo a cerrar los issues abiertos actualmente para abrir otros nuevos que me permitan construir el código adecuadamente.

2022-11-28 17:05 UTC, JJ commented on src/deuda.py
> +    pass
Me temo que `pass` no representa todas esas cuatro líneas que has escrito arriba. Si el comentario no se corresponde al código, están los dos mal, el código y el comentario.
Por otro lado, me refiero al comentario de arriba. ¿"Creo `deuda.py`" incluye la justificación de por qué has escrito este comentario?

2022-11-28 17:37 UTC, danielsp13 commented on src/deuda.py
> +    pass
desde luego que no. no tengo nada que objetar aquí

2022-11-28 17:45 UTC, danielsp13 commented on src/deuda.py
> +class deuda:
La documentación de la solución lo haré en su correspondiente fichero, y acto seguido lo justificaré en el commit que estoy haciendo. De acuerdo.

Pero la verdad que yo por más que he leído las buenas prácticas sobre los commits y cómo realizarlos a mi me sigue sin quedar claro cómo tiene que ser un commit en lo que al propio mensaje se refiere para lo que me estás pidiendo. En el ejemplo del comentario que me ha hecho debajo, lo entiendo. Pero si yo por ejemplo hubiese definido este objeto valor completo, sigo sin saber qué es lo que tengo que poner exactamente en el mensaje, en la descripción del mismo sí que lo tengo claro.

2022-11-28 17:56 UTC, JJ commented on src/deuda.py
> +class deuda:
Si sólo haces eso, con un :sparkles: es suficiente. Pero la cuestión es que las buenas prácticas son las mejores prácticas. Lo que te está diciendo la buena práctica *de commit* es que tengas unas buenas prácticas *de desarrollo atómico de acuerdo con los issues*. La buena práctica de siempre asociar un issue a un commit no es para que pongas un numerito, es para que no desarrolles código si no tienes claro para qué lo estás desarrollando. La práctica de poner mensajes informativos y que expliquen por qué estás haciendo algo, lo que viene a decir es que si no hay nada que informar y ya está en el propio commit, *es que no estás haciendo nada y por tanto tienes que hacer algo más para el commit*
Las buenas prácticas tratan de asegurarse de que la calidad esté en todos los aspectos del proceso, en general, y por eso hay que aplicarlas y entenderlas. Aplicarlas sin entenderlas también me vale, porque al final hace que se vayan entendiendo si las aplicas.

2022-11-28 18:59 UTC, danielsp13 commented on src/deuda.py
> +class deuda:
me he tomado un tiempo para leer tanto esto, como nuevamente las buenas prácticas del enlace de la documentación, como los errores frecuentes del objetivo 2 de esta semana. ahora sí que creo que me ha quedado claro. gracias.

2022-11-28 19:00 UTC, danielsp13 commented
@JJ tengo una duda con respecto a los issues que tengo abiertos y que no sirven, ¿puedo eliminarlos y dejar sólo los que sirvan?

2022-11-28 19:18 UTC, danielsp13 commented
(mientras tanto, empiezo de cero para intentar seguir las mejores prácticas, nuevamente. Desmarco también todos los items del cuerpo del PR ya que no cumplo ahora mismo con nada de lo que digo).

2022-11-28 19:18 UTC, JJ commented
> @JJ tengo una duda con respecto a los issues que tengo abiertos y que no sirven, ¿puedo eliminarlos y dejar sólo los que sirvan? (aunque tengan correcciones suyas)

No, no elimines issues. Ciérralos desde un commit cuando borres el código que hayas desarrollado siguiéndolos (más o menos)

2022-11-28 21:24 UTC, danielsp13 commented
Creo que ahora sí he seguido los pasos correctos. He optado por tener en cuenta finalmente la historia de usuario [HU3](https://github.com/jesusjmma/Proyecto-Infraestructura-Virtual/issues/4), que era la que mejor me permitía identificar las estructuras necesarias para la representación del modelo.

Primero he planteado los problemas referentes a los gastos #11 , y a continuación con los usuarios #13 .
Segundo, he propuesto la solución en código, con los commits adecuados. 
Tercero, he documentado la justificación de mis elecciones en cuanto a por qué *gasto* debe ser un objeto valor, y por qué *usuario* es una entidad. Disponible en [README](src/README.md).
Finalmente, he terminado de resolver los problemas describiendo en docstring lo que es cada clase.

2022-11-28 21:26 UTC, danielsp13 commented
@jesusjmma y @JJ , estaré al tanto de vuestra revisión. Gracias.

2022-11-29 09:44 UTC, JJ approved these changes
Voy a optar por aprobar, aunque es posible que etengas que hacer algún cambio antes de que @jesusjmma lo apruebe.

2022-11-29 09:44 UTC, JJ commented on src/usuario.py
> +        self.__nickname = nickname.lower()
¿Dónde dice que esto puede rescibirse sin normalizar, y que hay que normalizarlo?

2022-11-29 09:44 UTC, JJ commented on src/usuario.py
> +    def getNickname(self):
Qué manía con los getters y setters. ¿Dónde lo pide? ¿Por qué?
Aparte de que un getter de un atributo es algo trivial y no forma parte dle modelo.

2022-11-29 10:09 UTC, jesusjmma approved these changes
Buenos días @danielsp13.

Por mí está bien. Ahora el contenido se ha ajustado más a lo descrito en #4.

También he revisado uno a uno y veo que sigues cumpliendo con toda la lista de comprobación, así que fenomenal.

Un saludo y ¡enhorabuena!

2022-12-08 18:39 UTC, merged